version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      next-react:
        patterns:
          - "next"
          - "react"
          - "react-dom"
          - "eslint-config-next"
      three-r3f:
        patterns:
          - "three"
          - "@react-three/*"
          - "@types/three"
